# Generated by Django 5.2.8 on 2025-12-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='no title', max_length=200),
            preserve_default=False,
        ),
    ]
