# Generated by Django 5.2.8 on 2025-12-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_review_name_alter_review_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='message',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
        migrations.AddField(
            model_name='review',
            name='category',
            field=models.CharField(choices=[('movie', '영화'), ('book', '도서'), ('music', '노래')], default='movie', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
