# Generated by Django 5.2.8 on 2025-12-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_message_review_content_remove_review_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.CharField(default='movie', max_length=50),
            preserve_default=False,
        ),
    ]
