# Generated by Django 5.2.8 on 2025-12-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_personallist_personallistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='personallist',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='plist_covers/'),
        ),
    ]
