# Generated by Django 5.2.8 on 2025-12-06 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_personallist_cover_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='personallist',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='personallist',
            name='reviews',
            field=models.ManyToManyField(through='main.PersonalListItem', to='main.review'),
        ),
        migrations.AddField(
            model_name='personallist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
